name: build

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        python: ["3.7", "3.8", "3.9"]
        os: [ubuntu-latest, windows-latest]
        include:
          - python: "3.7"
            tox_env: "py37-pytest30"
          - python: "3.8"
            tox_env: "py38-pytest30"
          - python: "3.9"
            tox_env: "py39-pytest30"

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: MatteoH2O1999/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Test
      run: |
        pipx run tox -e ${{ matrix.tox_env }}  

  deploy:

    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')

    runs-on: ubuntu-latest

    needs: build

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: MatteoH2O1999/setup-python@v1
      with:
        python-version: "3.7"
    - name: setup timemachine
      run: |
        pip config set global.index-url "https://:2021-11-04T22:17:14.391Z@time-machines-pypi.sealsecurity.io/"
    - name: tag version
      run: |
        git tag 1.11.0
        git push origin 1.11.0   
    - name: Install wheel
      run: |
        python -m pip install --upgrade pip
        pip install wheel
    - name: Build package
      run: |
        python setup.py sdist bdist_wheel
    - name: "Upload build"
      uses: actions/upload-artifact@v4
      with:
        name: "dist"
        path: "dist"